"""Link passwords to access groups

Revision ID: 3c48cd86dc6f
Revises: a76a5a6beab3
Create Date: 2025-07-17 11:58:30.514099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c48cd86dc6f'
down_revision = 'a76a5a6beab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_group_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_password_access_group', 'access_group', ['access_group_id'], ['id'])
        batch_op.create_unique_constraint("uq_password_value", ['value'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('access_group_id')

    # ### end Alembic commands ###
