"""Initial database creation

Revision ID: 6c2f102a4c0a
Revises: 
Create Date: 2025-07-10 20:59:01.601000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2f102a4c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_24h', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('day_sun', sa.Boolean(), nullable=True),
    sa.Column('day_mon', sa.Boolean(), nullable=True),
    sa.Column('day_tue', sa.Boolean(), nullable=True),
    sa.Column('day_wed', sa.Boolean(), nullable=True),
    sa.Column('day_thu', sa.Boolean(), nullable=True),
    sa.Column('day_fri', sa.Boolean(), nullable=True),
    sa.Column('day_sat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('esphome_hostname', sa.String(length=100), nullable=False),
    sa.Column('esphome_api_key', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('esphome_hostname'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_group_id'], ['access_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('finger_used', sa.String(length=50), nullable=True),
    sa.Column('matched_finger_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fingerprint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finger_id_on_sensor', sa.Integer(), nullable=False),
    sa.Column('finger_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finger_id_on_sensor', 'zone_id', name='_finger_id_zone_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fingerprint')
    op.drop_table('access_log')
    op.drop_table('user')
    op.drop_table('zone')
    op.drop_table('admin_user')
    op.drop_table('access_group')
    # ### end Alembic commands ###
