# /addons/controle_biometrico/build.yaml
build_from:
  aarch64: "ghcr.io/hassio-addons/base-python:17.0.0"
  amd64: "ghcr.io/hassio-addons/base-python:17.0.0"
  armv7: "ghcr.io/hassio-addons/base-python:17.0.0"